name: Unit Test

on:
  workflow_dispatch: # because sometimes you just want to force a branch to have tests run
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - main
      - "bmaden-usds/*"

env:
  JAVA_VERSION: 18

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v3
      - name: Set up JDK ${{env.JAVA_VERSION}}
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: ${{env.JAVA_VERSION}}
          cache: gradle
      - name: Run unit tests
        run: ./gradlew test